const UPDATE_EMAIL = 'UPDATE_EMAIL';
const INIT_QUESTIONS = 'INIT_QUESTIONS';
const LOGIN = 'LOGIN';
const SELECT_ANSWER = 'SELECT_ANSWER';
const UPDATE_TOKEN = 'UPDATE_TOKEN';

export { UPDATE_EMAIL, INIT_QUESTIONS, LOGIN, SELECT_ANSWER, UPDATE_TOKEN };
